"""KVN-02: migration'lar şemayı eksiksiz ve geri alınabilir şekilde kurar."""

from __future__ import annotations

from datetime import UTC, date, datetime
from decimal import Decimal
from pathlib import Path
from typing import cast

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import Engine, Numeric, create_engine, inspect, text
from sqlalchemy.engine import URL
from sqlalchemy.orm import Session

from app.core.db import Base
from app.models.partitions import ensure_monthly_partition, partition_name
from tests.conftest import BACKEND_DIR


def _alembic_config(url: URL) -> Config:
    config = Config(str(BACKEND_DIR / "alembic.ini"))
    config.set_main_option("script_location", str(BACKEND_DIR / "alembic"))
    config.set_main_option("sqlalchemy.url", url.render_as_string(hide_password=False))
    return config


def test_all_model_tables_exist(db_engine: Engine) -> None:
    """Modeldeki her tablo migration sonrası veritabanında bulunmalı."""
    existing = set(inspect(db_engine).get_table_names())
    missing = set(Base.metadata.tables) - existing
    assert not missing, f"migration'da eksik tablolar: {sorted(missing)}"


def test_schema_matches_models(db_url: URL, db_engine: Engine) -> None:
    """Model ile şema arasında sürüklenme (drift) olmamalı — `alembic check`."""
    try:
        command.check(_alembic_config(db_url))
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - drift olursa testin mesajı
        pytest.fail(f"model/şema uyuşmuyor: {exc}")


def test_migration_downgrades_and_upgrades_cleanly(db_url: URL) -> None:
    """Geri alma + yeniden kurma çalışır (enum tipleri dahil temizlenir)."""
    scratch_url = db_url.set(database=f"{db_url.database}_cycle")
    admin = create_engine(db_url.set(database="postgres"), isolation_level="AUTOCOMMIT")
    with admin.connect() as connection:
        connection.execute(text(f'DROP DATABASE IF EXISTS "{scratch_url.database}"'))
        connection.execute(text(f'CREATE DATABASE "{scratch_url.database}"'))

    config = _alembic_config(scratch_url)
    try:
        command.upgrade(config, "head")
        command.downgrade(config, "base")
        # Enum tipleri düşmediyse bu ikinci upgrade "type already exists" ile patlar.
        command.upgrade(config, "head")
    finally:
        with admin.connect() as connection:
            connection.execute(text(f'DROP DATABASE IF EXISTS "{scratch_url.database}"'))
        admin.dispose()


def test_money_columns_use_expected_precision(db_engine: Engine) -> None:
    """Para disiplini (CLAUDE.md §1): tutar NUMERIC(14,4), ortalama maliyet NUMERIC(14,6)."""
    inspector = inspect(db_engine)
    columns = {column["name"]: column for column in inspector.get_columns("line_profit")}
    profit = cast(Numeric[Decimal], columns["profit"]["type"])
    assert (profit.precision, profit.scale) == (14, 4)

    ledger = {column["name"]: column for column in inspector.get_columns("inventory_ledger")}
    avg_cost = cast(Numeric[Decimal], ledger["avg_cost_after"]["type"])
    assert (avg_cost.precision, avg_cost.scale) == (14, 6)


def test_raw_events_is_partitioned(db_engine: Engine) -> None:
    """`raw_events` aya göre partition'lı olmalı (spec §5.3)."""
    with db_engine.connect() as connection:
        kind = connection.execute(
            text("SELECT relkind FROM pg_class WHERE relname = 'raw_events'")
        ).scalar()
        assert kind == "p", "raw_events partition'lı tablo değil"

        partitions = connection.execute(
            text(
                "SELECT count(*) FROM pg_inherits i "
                "JOIN pg_class parent ON parent.oid = i.inhparent "
                "WHERE parent.relname = 'raw_events'"
            )
        ).scalar()
        assert partitions and partitions > 12


def test_raw_event_insert_routes_to_month_partition(db_session: Session) -> None:
    """Yazılan ham olay doğru ay partition'ına düşer."""
    tenant_id = db_session.execute(
        text(
            "INSERT INTO tenants (id, slug, name, created_at) "
            "VALUES (gen_random_uuid(), 'raw-test', 'Raw Test', now()) RETURNING id"
        )
    ).scalar_one()
    brand_id = db_session.execute(
        text(
            "INSERT INTO brands (id, tenant_id, slug, name, created_at) "
            "VALUES (gen_random_uuid(), :tenant, 'test', 'Test', now()) RETURNING id"
        ),
        {"tenant": tenant_id},
    ).scalar_one()
    channel_id = db_session.execute(
        text(
            "INSERT INTO channels (id, code, name) "
            "VALUES (gen_random_uuid(), 'n11', 'N11') "
            "ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name RETURNING id"
        )
    ).scalar_one()
    store_id = db_session.execute(
        text(
            "INSERT INTO stores (id, tenant_id, brand_id, channel_id, name, is_active, created_at) "
            "VALUES (gen_random_uuid(), :tenant, :brand, :channel, 'Test', true, now()) "
            "RETURNING id"
        ),
        {"tenant": tenant_id, "brand": brand_id, "channel": channel_id},
    ).scalar_one()

    moment = datetime(2026, 3, 15, 10, 30, tzinfo=UTC)
    db_session.execute(
        text(
            "INSERT INTO raw_events (fetched_at, tenant_id, store_id, event_type, external_id, payload) "
            "VALUES (:fetched_at, :tenant, :store, 'order', 'X-1', '{}'::jsonb)"
        ),
        {"fetched_at": moment, "tenant": tenant_id, "store": store_id},
    )
    routed = db_session.execute(
        text("SELECT count(*) FROM raw_events_2026_03 WHERE external_id = 'X-1'")
    ).scalar()
    assert routed == 1


def test_ensure_monthly_partition_creates_missing_month(db_engine: Engine) -> None:
    """İleri tarihli ay için partition açılabilir (KVN-06 zamanlanmış job'ı bunu kullanacak)."""
    far_future = date(2031, 7, 9)
    with db_engine.begin() as connection:
        name = ensure_monthly_partition(connection, far_future)
        assert name == partition_name(date(2031, 7, 1))
        exists = connection.execute(
            text("SELECT 1 FROM pg_class WHERE relname = :name"), {"name": name}
        ).scalar()
        assert exists == 1
        # İkinci çağrı hata vermez (IF NOT EXISTS).
        ensure_monthly_partition(connection, far_future)
        connection.execute(text(f"DROP TABLE {name}"))


def test_single_migration_head() -> None:
    """Tek bir head olmalı — dallanmış migration geçmişi CI'da fark edilir."""
    versions = list((BACKEND_DIR / "alembic" / "versions").glob("*.py"))
    assert versions, "hiç migration yok"
    down_revisions = {
        Path(path)
        .read_text(encoding="utf-8")
        .split("down_revision: str | None = ")[1]
        .split("\n")[0]
        for path in versions
    }
    assert len(down_revisions) == len(versions), "birden fazla migration aynı parent'a bağlı"
