"""ilk şema (KVN-02)

Revision ID: 0325f904fbd8
Revises:
Create Date: 2026-08-18 17:33:37.475917+03:00
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import date

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0325f904fbd8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


ENUM_TYPES = (
    "alert_severity",
    "channel_code",
    "commission_mode",
    "commission_scope",
    "commission_source",
    "cost_source",
    "cost_state",
    "diff_status",
    "draft_status",
    "import_cost_item_type",
    "import_file_status",
    "inventory_movement",
    "invoice_status",
    "match_status",
    "order_status",
    "settlement_record_type",
    "shipping_payer",
    "user_role",
)
"""Tablolarla birlikte oluşan Postgres enum tipleri; downgrade'de elle düşürülür."""


START_MONTH = date(2026, 1, 1)
"""Açılışta oluşturulan ilk partition ayı — bundan öncesi DEFAULT partition'a düşer."""

MONTHS_AHEAD = 24
"""Kaç aylık partition önden açılsın."""


def monthly_partition_statements(start: date, months: int) -> list[str]:
    """`raw_events` için aylık partition CREATE ifadeleri üretir."""
    statements: list[str] = []
    cursor = start
    for _ in range(months):
        nxt = (
            date(cursor.year + 1, 1, 1)
            if cursor.month == 12
            else date(cursor.year, cursor.month + 1, 1)
        )
        statements.append(
            f"CREATE TABLE IF NOT EXISTS raw_events_{cursor:%Y_%m} PARTITION OF raw_events "
            f"FOR VALUES FROM ('{cursor.isoformat()}') TO ('{nxt.isoformat()}')"
        )
        cursor = nxt
    return statements


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "code",
            sa.Enum("trendyol", "hepsiburada", "n11", "shopify", "manual", name="channel_code"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channels")),
        sa.UniqueConstraint("code", name=op.f("uq_channels_code")),
    )
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenants_slug")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_ref", sa.String(length=200), nullable=True),
        sa.Column("detail", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_audit_log_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_tenant_id"), "audit_log", ["tenant_id"], unique=False)
    op.create_table(
        "brands",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("min_margin_floor_pct", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("default_vat_rate", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_brands_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brands")),
        sa.UniqueConstraint("tenant_id", "slug", name="uq_brands_tenant_slug"),
    )
    op.create_index(op.f("ix_brands_tenant_id"), "brands", ["tenant_id"], unique=False)
    op.create_table(
        "suppliers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("vkn", sa.String(length=20), nullable=True),
        sa.Column("default_currency", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_suppliers_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
        sa.UniqueConstraint("tenant_id", "name", name="uq_suppliers_tenant_name"),
    )
    op.create_index(op.f("ix_suppliers_tenant_id"), "suppliers", ["tenant_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_holding_viewer", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_users_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("tenant_id", "email", name="uq_users_tenant_email"),
    )
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=60), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("info", "warning", "critical", name="alert_severity"),
            nullable=False,
        ),
        sa.Column("entity_ref", sa.String(length=200), nullable=True),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_alerts_brand_id_brands"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_alerts_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index(op.f("ix_alerts_brand_id"), "alerts", ["brand_id"], unique=False)
    op.create_index(op.f("ix_alerts_tenant_id"), "alerts", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_alerts_type"), "alerts", ["type"], unique=False)
    op.create_table(
        "brand_features",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("feature_code", sa.String(length=50), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_brand_features_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brand_features")),
        sa.UniqueConstraint("brand_id", "feature_code", name="uq_brand_features_brand_feature"),
    )
    op.create_index(
        op.f("ix_brand_features_brand_id"), "brand_features", ["brand_id"], unique=False
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("tier", sa.String(length=50), nullable=True),
        sa.Column("default_discount_pct", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_customers_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_customers_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
    )
    op.create_index(op.f("ix_customers_brand_id"), "customers", ["brand_id"], unique=False)
    op.create_index(op.f("ix_customers_tenant_id"), "customers", ["tenant_id"], unique=False)
    op.create_table(
        "import_batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("filename", sa.String(length=300), nullable=False),
        sa.Column("user", sa.String(length=200), nullable=True),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("yeni", sa.Integer(), nullable=False),
        sa.Column("guncelleme", sa.Integer(), nullable=False),
        sa.Column("hata", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_import_batches_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_import_batches_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
    )
    op.create_index(
        op.f("ix_import_batches_brand_id"), "import_batches", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_import_batches_tenant_id"), "import_batches", ["tenant_id"], unique=False
    )
    op.create_table(
        "import_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("file_no", sa.String(length=120), nullable=False),
        sa.Column("beyanname_no", sa.String(length=120), nullable=True),
        sa.Column("beyanname_date", sa.Date(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("fx_rate_beyanname", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("import_vat_paid", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column(
            "status", sa.Enum("open", "confirmed", name="import_file_status"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_import_files_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_import_files_supplier_id_suppliers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_import_files_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_files")),
        sa.UniqueConstraint("tenant_id", "file_no", name="uq_import_files_tenant_no"),
    )
    op.create_index(op.f("ix_import_files_brand_id"), "import_files", ["brand_id"], unique=False)
    op.create_index(
        op.f("ix_import_files_supplier_id"), "import_files", ["supplier_id"], unique=False
    )
    op.create_index(op.f("ix_import_files_tenant_id"), "import_files", ["tenant_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("barcode", sa.String(length=64), nullable=True),
        sa.Column("category", sa.String(length=200), nullable=True),
        sa.Column("vat_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("msrp", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("min_margin_floor_pct", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_products_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_products_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("tenant_id", "brand_id", "sku", name="uq_products_brand_sku"),
    )
    op.create_index(op.f("ix_products_barcode"), "products", ["barcode"], unique=False)
    op.create_index(op.f("ix_products_brand_id"), "products", ["brand_id"], unique=False)
    op.create_index(op.f("ix_products_tenant_id"), "products", ["tenant_id"], unique=False)
    op.create_table(
        "purchase_invoices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("invoice_no", sa.String(length=120), nullable=False),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("fx_rate", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("landed_cost_extra", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("pdf_path", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum("parsed", "review", "confirmed", name="invoice_status"),
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_purchase_invoices_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_purchase_invoices_supplier_id_suppliers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_purchase_invoices_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_invoices")),
        sa.UniqueConstraint(
            "tenant_id", "supplier_id", "invoice_no", name="uq_purchase_invoices_supplier_no"
        ),
    )
    op.create_index(
        op.f("ix_purchase_invoices_brand_id"), "purchase_invoices", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_invoices_invoice_date"),
        "purchase_invoices",
        ["invoice_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_invoices_supplier_id"), "purchase_invoices", ["supplier_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_invoices_tenant_id"), "purchase_invoices", ["tenant_id"], unique=False
    )
    op.create_table(
        "stores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.Column("external_seller_id", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("service_fee_per_order", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_stores_brand_id_brands"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.id"],
            name=op.f("fk_stores_channel_id_channels"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_stores_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stores")),
        sa.UniqueConstraint(
            "tenant_id", "channel_id", "external_seller_id", name="uq_stores_tenant_channel_seller"
        ),
    )
    op.create_index(op.f("ix_stores_brand_id"), "stores", ["brand_id"], unique=False)
    op.create_index(op.f("ix_stores_channel_id"), "stores", ["channel_id"], unique=False)
    op.create_index(op.f("ix_stores_tenant_id"), "stores", ["tenant_id"], unique=False)
    op.create_table(
        "user_brand_roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Enum("viewer", "editor", "admin", name="user_role"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_user_brand_roles_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_brand_roles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_brand_roles")),
        sa.UniqueConstraint("user_id", "brand_id", name="uq_user_brand_roles_user_brand"),
    )
    op.create_index(
        op.f("ix_user_brand_roles_brand_id"), "user_brand_roles", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_brand_roles_user_id"), "user_brand_roles", ["user_id"], unique=False
    )
    op.create_table(
        "ad_spend",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("campaign_id", sa.String(length=120), nullable=True),
        sa.Column("campaign_name", sa.String(length=200), nullable=True),
        sa.Column("spend", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_ad_spend_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_ad_spend_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_ad_spend_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_ad_spend_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ad_spend")),
    )
    op.create_index(op.f("ix_ad_spend_brand_id"), "ad_spend", ["brand_id"], unique=False)
    op.create_index(op.f("ix_ad_spend_date"), "ad_spend", ["date"], unique=False)
    op.create_index(op.f("ix_ad_spend_product_id"), "ad_spend", ["product_id"], unique=False)
    op.create_index(op.f("ix_ad_spend_store_id"), "ad_spend", ["store_id"], unique=False)
    op.create_index(op.f("ix_ad_spend_tenant_id"), "ad_spend", ["tenant_id"], unique=False)
    op.create_table(
        "cargo_invoices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("invoice_no", sa.String(length=120), nullable=False),
        sa.Column("period", sa.String(length=20), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("lines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_cargo_invoices_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_cargo_invoices_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_cargo_invoices_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cargo_invoices")),
        sa.UniqueConstraint("store_id", "invoice_no", name="uq_cargo_invoices_store_invoice"),
    )
    op.create_index(
        op.f("ix_cargo_invoices_brand_id"), "cargo_invoices", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_cargo_invoices_store_id"), "cargo_invoices", ["store_id"], unique=False
    )
    op.create_index(
        op.f("ix_cargo_invoices_tenant_id"), "cargo_invoices", ["tenant_id"], unique=False
    )
    op.create_table(
        "commission_changes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("category_code", sa.String(length=200), nullable=True),
        sa.Column("old_rate", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("new_rate", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("monthly_profit_impact", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("alert_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alerts.id"],
            name=op.f("fk_commission_changes_alert_id_alerts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_commission_changes_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_commission_changes_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commission_changes")),
    )
    op.create_index(
        op.f("ix_commission_changes_alert_id"), "commission_changes", ["alert_id"], unique=False
    )
    op.create_index(
        op.f("ix_commission_changes_product_id"), "commission_changes", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_commission_changes_store_id"), "commission_changes", ["store_id"], unique=False
    )
    op.create_table(
        "commission_rates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("scope", sa.Enum("product", "category", name="commission_scope"), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("category_code", sa.String(length=200), nullable=True),
        sa.Column("rate", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "settlement_actual",
                "api_product",
                "api_category",
                "manual_tariff_upload",
                "manual",
                name="commission_source",
            ),
            nullable=False,
        ),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("snapshot_date", sa.Date(), nullable=True),
        sa.Column("is_campaign_period", sa.Boolean(), nullable=False),
        sa.Column("campaign_name", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_commission_rates_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_commission_rates_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commission_rates")),
    )
    op.create_index(
        op.f("ix_commission_rates_category_code"),
        "commission_rates",
        ["category_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_commission_rates_product_id"), "commission_rates", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_commission_rates_store_id"), "commission_rates", ["store_id"], unique=False
    )
    op.create_index(
        op.f("ix_commission_rates_valid_from"), "commission_rates", ["valid_from"], unique=False
    )
    op.create_table(
        "import_cost_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("import_file_id", sa.UUID(), nullable=False),
        sa.Column(
            "item_type",
            sa.Enum(
                "mal_bedeli",
                "navlun",
                "sigorta",
                "gumruk_vergisi",
                "gumruk_musavirligi",
                "ardiye_liman",
                "diger",
                name="import_cost_item_type",
            ),
            nullable=False,
        ),
        sa.Column("amount_original", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("amount_try", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("vendor", sa.String(length=200), nullable=True),
        sa.Column("doc_ref", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["import_file_id"],
            ["import_files.id"],
            name=op.f("fk_import_cost_items_import_file_id_import_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_cost_items")),
    )
    op.create_index(
        op.f("ix_import_cost_items_import_file_id"),
        "import_cost_items",
        ["import_file_id"],
        unique=False,
    )
    op.create_table(
        "inventory_ledger",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column(
            "movement",
            sa.Enum(
                "opening",
                "purchase_in",
                "sale_out",
                "return_in",
                "return_out",
                "adjustment",
                "damage",
                name="inventory_movement",
            ),
            nullable=False,
        ),
        sa.Column("qty_delta", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("unit_cost_at_movement", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("avg_cost_after", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("on_hand_after", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("ref_type", sa.String(length=60), nullable=True),
        sa.Column("ref_id", sa.String(length=120), nullable=True),
        sa.Column("reason", sa.String(length=300), nullable=True),
        sa.Column("moved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_inventory_ledger_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_inventory_ledger_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_inventory_ledger_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_ledger")),
    )
    op.create_index(
        op.f("ix_inventory_ledger_brand_id"), "inventory_ledger", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_ledger_moved_at"), "inventory_ledger", ["moved_at"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_ledger_product_id"), "inventory_ledger", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_ledger_tenant_id"), "inventory_ledger", ["tenant_id"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("external_order_id", sa.String(length=120), nullable=False),
        sa.Column("order_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "picking",
                "shipped",
                "delivered",
                "cancelled",
                "returned",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column("customer_city", sa.String(length=100), nullable=True),
        sa.Column("gross_total", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_orders_brand_id_brands"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_orders_store_id_stores"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_orders_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint(
            "tenant_id", "store_id", "external_order_id", name="uq_orders_tenant_store_external"
        ),
    )
    op.create_index(op.f("ix_orders_brand_id"), "orders", ["brand_id"], unique=False)
    op.create_index(op.f("ix_orders_order_date"), "orders", ["order_date"], unique=False)
    op.create_index(op.f("ix_orders_store_id"), "orders", ["store_id"], unique=False)
    op.create_index(op.f("ix_orders_tenant_id"), "orders", ["tenant_id"], unique=False)
    op.create_table(
        "pricing_scenarios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("satis_fiyati", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("kampanya_indirim_pct", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("kampanya_satici_pay_pct", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            "kargo_kim_oder",
            sa.Enum("satici", "alici", "platform", name="shipping_payer"),
            nullable=False,
        ),
        sa.Column("adet_varsayimi", sa.Integer(), nullable=False),
        sa.Column(
            "commission_mode",
            sa.Enum("current", "pinned", "future_tariff", name="commission_mode"),
            nullable=False,
        ),
        sa.Column("pinned_commission_rate", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("future_tariff_date", sa.Date(), nullable=True),
        sa.Column("created_by", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_pricing_scenarios_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_pricing_scenarios_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_pricing_scenarios_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_scenarios")),
    )
    op.create_index(
        op.f("ix_pricing_scenarios_brand_id"), "pricing_scenarios", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_pricing_scenarios_product_id"), "pricing_scenarios", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_pricing_scenarios_tenant_id"), "pricing_scenarios", ["tenant_id"], unique=False
    )
    op.create_table(
        "product_channel_map",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("external_product_id", sa.String(length=120), nullable=False),
        sa.Column("external_barcode", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_channel_map_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_product_channel_map_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_channel_map")),
        sa.UniqueConstraint("store_id", "external_product_id", name="uq_pcm_store_external"),
    )
    op.create_index(
        op.f("ix_product_channel_map_product_id"),
        "product_channel_map",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_channel_map_store_id"), "product_channel_map", ["store_id"], unique=False
    )
    op.create_table(
        "product_drafts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("sku_onerisi", sa.String(length=100), nullable=True),
        sa.Column("alis_maliyeti", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("hedef_satis_fiyati", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("kanal", sa.String(length=50), nullable=True),
        sa.Column("vat_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("desi", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column(
            "status", sa.Enum("draft", "promoted", "discarded", name="draft_status"), nullable=False
        ),
        sa.Column("promoted_product_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_product_drafts_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["promoted_product_id"],
            ["products.id"],
            name=op.f("fk_product_drafts_promoted_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_product_drafts_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_drafts")),
    )
    op.create_index(
        op.f("ix_product_drafts_brand_id"), "product_drafts", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_drafts_promoted_product_id"),
        "product_drafts",
        ["promoted_product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_drafts_tenant_id"), "product_drafts", ["tenant_id"], unique=False
    )
    op.create_table(
        "promotions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("seller_share_rate", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_promotions_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_promotions_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_promotions_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promotions")),
    )
    op.create_index(op.f("ix_promotions_brand_id"), "promotions", ["brand_id"], unique=False)
    op.create_index(op.f("ix_promotions_store_id"), "promotions", ["store_id"], unique=False)
    op.create_index(op.f("ix_promotions_tenant_id"), "promotions", ["tenant_id"], unique=False)
    op.create_table(
        "purchase_invoice_lines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("raw_text", sa.String(length=500), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("qty", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("unit_price_original", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("unit_price_try", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("vat_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("landed_unit_cost_try", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column(
            "match_status",
            sa.Enum("auto", "manual", "unmatched", name="match_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["purchase_invoices.id"],
            name=op.f("fk_purchase_invoice_lines_invoice_id_purchase_invoices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_purchase_invoice_lines_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_invoice_lines")),
    )
    op.create_index(
        op.f("ix_purchase_invoice_lines_invoice_id"),
        "purchase_invoice_lines",
        ["invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_invoice_lines_product_id"),
        "purchase_invoice_lines",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "raw_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=120), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_raw_events_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_raw_events_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", "fetched_at", name=op.f("pk_raw_events")),
        sa.UniqueConstraint(
            "tenant_id",
            "store_id",
            "event_type",
            "external_id",
            "fetched_at",
            name="uq_raw_events_identity",
        ),
        postgresql_partition_by="RANGE (fetched_at)",
    )
    op.create_index(op.f("ix_raw_events_store_id"), "raw_events", ["store_id"], unique=False)
    op.create_index(op.f("ix_raw_events_tenant_id"), "raw_events", ["tenant_id"], unique=False)
    # raw_events aya göre partition'lıdır (spec §5.3). Yazma anında uygun partition
    # yoksa INSERT başarısız olur; bu yüzden hem yakın aylar hem de güvenlik ağı
    # olarak DEFAULT partition oluşturulur. Yeni aylar `ensure_monthly_partition`
    # ile açılır (bkz. app/models/partitions.py).
    op.execute("CREATE TABLE IF NOT EXISTS raw_events_default PARTITION OF raw_events DEFAULT")
    for statement in monthly_partition_statements(START_MONTH, MONTHS_AHEAD):
        op.execute(statement)
    op.create_table(
        "sku_cost_state",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("on_hand_qty", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("avg_cost", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("last_movement_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_sku_cost_state_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("product_id", name=op.f("pk_sku_cost_state")),
    )
    op.create_table(
        "sku_costs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "source",
            sa.Enum("manual", "invoice", "erp", "invoice_wac", name="cost_source"),
            nullable=False,
        ),
        sa.Column("invoice_ref", sa.String(length=120), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_sku_costs_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sku_costs")),
    )
    op.create_index(
        op.f("ix_sku_costs_effective_from"), "sku_costs", ["effective_from"], unique=False
    )
    op.create_index(op.f("ix_sku_costs_product_id"), "sku_costs", ["product_id"], unique=False)
    op.create_table(
        "sku_logistics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("desi", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("default_carrier", sa.String(length=100), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_sku_logistics_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sku_logistics")),
    )
    op.create_index(
        op.f("ix_sku_logistics_product_id"), "sku_logistics", ["product_id"], unique=False
    )
    op.create_table(
        "store_credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("encrypted_payload", sa.LargeBinary(), nullable=False),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_store_credentials_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_credentials")),
    )
    op.create_index(
        op.f("ix_store_credentials_store_id"), "store_credentials", ["store_id"], unique=False
    )
    op.create_table(
        "supplier_payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("import_file_id", sa.UUID(), nullable=True),
        sa.Column("invoice_id", sa.UUID(), nullable=True),
        sa.Column("pay_date", sa.Date(), nullable=False),
        sa.Column("amount_original", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("fx_rate_payment", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("fx_diff_try", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_supplier_payments_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["import_file_id"],
            ["import_files.id"],
            name=op.f("fk_supplier_payments_import_file_id_import_files"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["purchase_invoices.id"],
            name=op.f("fk_supplier_payments_invoice_id_purchase_invoices"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_supplier_payments_supplier_id_suppliers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_supplier_payments_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplier_payments")),
    )
    op.create_index(
        op.f("ix_supplier_payments_brand_id"), "supplier_payments", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_supplier_payments_import_file_id"),
        "supplier_payments",
        ["import_file_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_payments_invoice_id"), "supplier_payments", ["invoice_id"], unique=False
    )
    op.create_index(
        op.f("ix_supplier_payments_supplier_id"), "supplier_payments", ["supplier_id"], unique=False
    )
    op.create_index(
        op.f("ix_supplier_payments_tenant_id"), "supplier_payments", ["tenant_id"], unique=False
    )
    op.create_table(
        "supplier_product_map",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("raw_name_normalized", sa.String(length=400), nullable=False),
        sa.Column("barcode", sa.String(length=64), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_supplier_product_map_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_supplier_product_map_supplier_id_suppliers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplier_product_map")),
        sa.UniqueConstraint(
            "supplier_id", "raw_name_normalized", name="uq_supplier_product_map_supplier_name"
        ),
    )
    op.create_index(
        op.f("ix_supplier_product_map_product_id"),
        "supplier_product_map",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_product_map_supplier_id"),
        "supplier_product_map",
        ["supplier_id"],
        unique=False,
    )
    op.create_table(
        "order_lines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("external_line_id", sa.String(length=120), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("unit_sale_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("line_gross", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("vat_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("commission_rate_used", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column(
            "commission_source",
            sa.Enum(
                "settlement_actual",
                "api_product",
                "api_category",
                "manual_tariff_upload",
                "manual",
                name="commission_source",
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "picking",
                "shipped",
                "delivered",
                "cancelled",
                "returned",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_order_lines_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_lines_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_order_lines_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_order_lines_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_lines")),
        sa.UniqueConstraint("order_id", "external_line_id", name="uq_order_lines_order_external"),
    )
    op.create_index(op.f("ix_order_lines_brand_id"), "order_lines", ["brand_id"], unique=False)
    op.create_index(op.f("ix_order_lines_order_id"), "order_lines", ["order_id"], unique=False)
    op.create_index(op.f("ix_order_lines_product_id"), "order_lines", ["product_id"], unique=False)
    op.create_index(op.f("ix_order_lines_tenant_id"), "order_lines", ["tenant_id"], unique=False)
    op.create_table(
        "shipments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("carrier", sa.String(length=100), nullable=True),
        sa.Column("desi_declared", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("desi_invoiced", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("cargo_cost_estimated", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("cargo_cost_actual", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("cost_state", sa.Enum("estimated", "actual", name="cost_state"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_shipments_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_shipments_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_shipments_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipments")),
    )
    op.create_index(op.f("ix_shipments_brand_id"), "shipments", ["brand_id"], unique=False)
    op.create_index(op.f("ix_shipments_order_id"), "shipments", ["order_id"], unique=False)
    op.create_index(op.f("ix_shipments_tenant_id"), "shipments", ["tenant_id"], unique=False)
    op.create_table(
        "line_profit",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("order_line_id", sa.UUID(), nullable=False),
        sa.Column("revenue_net_vat", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("cost_cogs", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("cost_commission", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("cost_cargo", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("cost_service_fee", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("cost_return", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("cost_ad_alloc", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("vat_net", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("profit", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("margin_pct", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column(
            "commission_source",
            sa.Enum(
                "settlement_actual",
                "api_product",
                "api_category",
                "manual_tariff_upload",
                "manual",
                name="commission_source",
            ),
            nullable=True,
        ),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_final", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_line_profit_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_line_id"],
            ["order_lines.id"],
            name=op.f("fk_line_profit_order_line_id_order_lines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_line_profit_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_line_profit")),
        sa.UniqueConstraint("order_line_id", name="uq_line_profit_order_line"),
    )
    op.create_index(op.f("ix_line_profit_brand_id"), "line_profit", ["brand_id"], unique=False)
    op.create_index(
        op.f("ix_line_profit_order_line_id"), "line_profit", ["order_line_id"], unique=False
    )
    op.create_index(op.f("ix_line_profit_tenant_id"), "line_profit", ["tenant_id"], unique=False)
    op.create_table(
        "profit_revisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("order_line_id", sa.UUID(), nullable=False),
        sa.Column("field", sa.String(length=60), nullable=False),
        sa.Column("old_value", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("new_value", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.Column("revised_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_profit_revisions_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_line_id"],
            ["order_lines.id"],
            name=op.f("fk_profit_revisions_order_line_id_order_lines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_profit_revisions_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profit_revisions")),
    )
    op.create_index(
        op.f("ix_profit_revisions_brand_id"), "profit_revisions", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_profit_revisions_order_line_id"),
        "profit_revisions",
        ["order_line_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_profit_revisions_tenant_id"), "profit_revisions", ["tenant_id"], unique=False
    )
    op.create_table(
        "returns",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("order_line_id", sa.UUID(), nullable=False),
        sa.Column("return_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=True),
        sa.Column("refund_amount", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("return_cargo_cost_estimated", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("return_cargo_cost_actual", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("cost_state", sa.Enum("estimated", "actual", name="cost_state"), nullable=False),
        sa.Column("restocked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_returns_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_line_id"],
            ["order_lines.id"],
            name=op.f("fk_returns_order_line_id_order_lines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_returns_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_returns")),
    )
    op.create_index(op.f("ix_returns_brand_id"), "returns", ["brand_id"], unique=False)
    op.create_index(op.f("ix_returns_order_line_id"), "returns", ["order_line_id"], unique=False)
    op.create_index(op.f("ix_returns_tenant_id"), "returns", ["tenant_id"], unique=False)
    op.create_table(
        "settlement_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("external_ref", sa.String(length=160), nullable=False),
        sa.Column(
            "record_type",
            sa.Enum(
                "sale",
                "commission",
                "cargo",
                "service_fee",
                "penalty",
                "ad_spend",
                "refund",
                "other",
                name="settlement_record_type",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("vat_amount", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("order_line_id", sa.UUID(), nullable=True),
        sa.Column("matched", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_settlement_records_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_line_id"],
            ["order_lines.id"],
            name=op.f("fk_settlement_records_order_line_id_order_lines"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_settlement_records_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_settlement_records_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settlement_records")),
        sa.UniqueConstraint(
            "tenant_id", "store_id", "external_ref", name="uq_settlement_tenant_store_ref"
        ),
    )
    op.create_index(
        op.f("ix_settlement_records_brand_id"), "settlement_records", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_settlement_records_order_line_id"),
        "settlement_records",
        ["order_line_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_settlement_records_store_id"), "settlement_records", ["store_id"], unique=False
    )
    op.create_index(
        op.f("ix_settlement_records_tenant_id"), "settlement_records", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_settlement_records_transaction_date"),
        "settlement_records",
        ["transaction_date"],
        unique=False,
    )
    op.create_table(
        "reconciliation_diffs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("period", sa.String(length=20), nullable=False),
        sa.Column("settlement_record_id", sa.UUID(), nullable=True),
        sa.Column("expected", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("actual", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("diff", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column(
            "status", sa.Enum("open", "explained", "resolved", name="diff_status"), nullable=False
        ),
        sa.Column("note", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_reconciliation_diffs_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["settlement_record_id"],
            ["settlement_records.id"],
            name=op.f("fk_reconciliation_diffs_settlement_record_id_settlement_records"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_reconciliation_diffs_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_reconciliation_diffs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliation_diffs")),
    )
    op.create_index(
        op.f("ix_reconciliation_diffs_brand_id"), "reconciliation_diffs", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_reconciliation_diffs_period"), "reconciliation_diffs", ["period"], unique=False
    )
    op.create_index(
        op.f("ix_reconciliation_diffs_settlement_record_id"),
        "reconciliation_diffs",
        ["settlement_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_diffs_store_id"), "reconciliation_diffs", ["store_id"], unique=False
    )
    op.create_index(
        op.f("ix_reconciliation_diffs_tenant_id"),
        "reconciliation_diffs",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reconciliation_diffs_tenant_id"), table_name="reconciliation_diffs")
    op.drop_index(op.f("ix_reconciliation_diffs_store_id"), table_name="reconciliation_diffs")
    op.drop_index(
        op.f("ix_reconciliation_diffs_settlement_record_id"), table_name="reconciliation_diffs"
    )
    op.drop_index(op.f("ix_reconciliation_diffs_period"), table_name="reconciliation_diffs")
    op.drop_index(op.f("ix_reconciliation_diffs_brand_id"), table_name="reconciliation_diffs")
    op.drop_table("reconciliation_diffs")
    op.drop_index(op.f("ix_settlement_records_transaction_date"), table_name="settlement_records")
    op.drop_index(op.f("ix_settlement_records_tenant_id"), table_name="settlement_records")
    op.drop_index(op.f("ix_settlement_records_store_id"), table_name="settlement_records")
    op.drop_index(op.f("ix_settlement_records_order_line_id"), table_name="settlement_records")
    op.drop_index(op.f("ix_settlement_records_brand_id"), table_name="settlement_records")
    op.drop_table("settlement_records")
    op.drop_index(op.f("ix_returns_tenant_id"), table_name="returns")
    op.drop_index(op.f("ix_returns_order_line_id"), table_name="returns")
    op.drop_index(op.f("ix_returns_brand_id"), table_name="returns")
    op.drop_table("returns")
    op.drop_index(op.f("ix_profit_revisions_tenant_id"), table_name="profit_revisions")
    op.drop_index(op.f("ix_profit_revisions_order_line_id"), table_name="profit_revisions")
    op.drop_index(op.f("ix_profit_revisions_brand_id"), table_name="profit_revisions")
    op.drop_table("profit_revisions")
    op.drop_index(op.f("ix_line_profit_tenant_id"), table_name="line_profit")
    op.drop_index(op.f("ix_line_profit_order_line_id"), table_name="line_profit")
    op.drop_index(op.f("ix_line_profit_brand_id"), table_name="line_profit")
    op.drop_table("line_profit")
    op.drop_index(op.f("ix_shipments_tenant_id"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_order_id"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_brand_id"), table_name="shipments")
    op.drop_table("shipments")
    op.drop_index(op.f("ix_order_lines_tenant_id"), table_name="order_lines")
    op.drop_index(op.f("ix_order_lines_product_id"), table_name="order_lines")
    op.drop_index(op.f("ix_order_lines_order_id"), table_name="order_lines")
    op.drop_index(op.f("ix_order_lines_brand_id"), table_name="order_lines")
    op.drop_table("order_lines")
    op.drop_index(op.f("ix_supplier_product_map_supplier_id"), table_name="supplier_product_map")
    op.drop_index(op.f("ix_supplier_product_map_product_id"), table_name="supplier_product_map")
    op.drop_table("supplier_product_map")
    op.drop_index(op.f("ix_supplier_payments_tenant_id"), table_name="supplier_payments")
    op.drop_index(op.f("ix_supplier_payments_supplier_id"), table_name="supplier_payments")
    op.drop_index(op.f("ix_supplier_payments_invoice_id"), table_name="supplier_payments")
    op.drop_index(op.f("ix_supplier_payments_import_file_id"), table_name="supplier_payments")
    op.drop_index(op.f("ix_supplier_payments_brand_id"), table_name="supplier_payments")
    op.drop_table("supplier_payments")
    op.drop_index(op.f("ix_store_credentials_store_id"), table_name="store_credentials")
    op.drop_table("store_credentials")
    op.drop_index(op.f("ix_sku_logistics_product_id"), table_name="sku_logistics")
    op.drop_table("sku_logistics")
    op.drop_index(op.f("ix_sku_costs_product_id"), table_name="sku_costs")
    op.drop_index(op.f("ix_sku_costs_effective_from"), table_name="sku_costs")
    op.drop_table("sku_costs")
    op.drop_table("sku_cost_state")
    op.drop_index(op.f("ix_raw_events_tenant_id"), table_name="raw_events")
    op.drop_index(op.f("ix_raw_events_store_id"), table_name="raw_events")
    op.drop_table("raw_events")
    op.drop_index(op.f("ix_purchase_invoice_lines_product_id"), table_name="purchase_invoice_lines")
    op.drop_index(op.f("ix_purchase_invoice_lines_invoice_id"), table_name="purchase_invoice_lines")
    op.drop_table("purchase_invoice_lines")
    op.drop_index(op.f("ix_promotions_tenant_id"), table_name="promotions")
    op.drop_index(op.f("ix_promotions_store_id"), table_name="promotions")
    op.drop_index(op.f("ix_promotions_brand_id"), table_name="promotions")
    op.drop_table("promotions")
    op.drop_index(op.f("ix_product_drafts_tenant_id"), table_name="product_drafts")
    op.drop_index(op.f("ix_product_drafts_promoted_product_id"), table_name="product_drafts")
    op.drop_index(op.f("ix_product_drafts_brand_id"), table_name="product_drafts")
    op.drop_table("product_drafts")
    op.drop_index(op.f("ix_product_channel_map_store_id"), table_name="product_channel_map")
    op.drop_index(op.f("ix_product_channel_map_product_id"), table_name="product_channel_map")
    op.drop_table("product_channel_map")
    op.drop_index(op.f("ix_pricing_scenarios_tenant_id"), table_name="pricing_scenarios")
    op.drop_index(op.f("ix_pricing_scenarios_product_id"), table_name="pricing_scenarios")
    op.drop_index(op.f("ix_pricing_scenarios_brand_id"), table_name="pricing_scenarios")
    op.drop_table("pricing_scenarios")
    op.drop_index(op.f("ix_orders_tenant_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_store_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_order_date"), table_name="orders")
    op.drop_index(op.f("ix_orders_brand_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_inventory_ledger_tenant_id"), table_name="inventory_ledger")
    op.drop_index(op.f("ix_inventory_ledger_product_id"), table_name="inventory_ledger")
    op.drop_index(op.f("ix_inventory_ledger_moved_at"), table_name="inventory_ledger")
    op.drop_index(op.f("ix_inventory_ledger_brand_id"), table_name="inventory_ledger")
    op.drop_table("inventory_ledger")
    op.drop_index(op.f("ix_import_cost_items_import_file_id"), table_name="import_cost_items")
    op.drop_table("import_cost_items")
    op.drop_index(op.f("ix_commission_rates_valid_from"), table_name="commission_rates")
    op.drop_index(op.f("ix_commission_rates_store_id"), table_name="commission_rates")
    op.drop_index(op.f("ix_commission_rates_product_id"), table_name="commission_rates")
    op.drop_index(op.f("ix_commission_rates_category_code"), table_name="commission_rates")
    op.drop_table("commission_rates")
    op.drop_index(op.f("ix_commission_changes_store_id"), table_name="commission_changes")
    op.drop_index(op.f("ix_commission_changes_product_id"), table_name="commission_changes")
    op.drop_index(op.f("ix_commission_changes_alert_id"), table_name="commission_changes")
    op.drop_table("commission_changes")
    op.drop_index(op.f("ix_cargo_invoices_tenant_id"), table_name="cargo_invoices")
    op.drop_index(op.f("ix_cargo_invoices_store_id"), table_name="cargo_invoices")
    op.drop_index(op.f("ix_cargo_invoices_brand_id"), table_name="cargo_invoices")
    op.drop_table("cargo_invoices")
    op.drop_index(op.f("ix_ad_spend_tenant_id"), table_name="ad_spend")
    op.drop_index(op.f("ix_ad_spend_store_id"), table_name="ad_spend")
    op.drop_index(op.f("ix_ad_spend_product_id"), table_name="ad_spend")
    op.drop_index(op.f("ix_ad_spend_date"), table_name="ad_spend")
    op.drop_index(op.f("ix_ad_spend_brand_id"), table_name="ad_spend")
    op.drop_table("ad_spend")
    op.drop_index(op.f("ix_user_brand_roles_user_id"), table_name="user_brand_roles")
    op.drop_index(op.f("ix_user_brand_roles_brand_id"), table_name="user_brand_roles")
    op.drop_table("user_brand_roles")
    op.drop_index(op.f("ix_stores_tenant_id"), table_name="stores")
    op.drop_index(op.f("ix_stores_channel_id"), table_name="stores")
    op.drop_index(op.f("ix_stores_brand_id"), table_name="stores")
    op.drop_table("stores")
    op.drop_index(op.f("ix_purchase_invoices_tenant_id"), table_name="purchase_invoices")
    op.drop_index(op.f("ix_purchase_invoices_supplier_id"), table_name="purchase_invoices")
    op.drop_index(op.f("ix_purchase_invoices_invoice_date"), table_name="purchase_invoices")
    op.drop_index(op.f("ix_purchase_invoices_brand_id"), table_name="purchase_invoices")
    op.drop_table("purchase_invoices")
    op.drop_index(op.f("ix_products_tenant_id"), table_name="products")
    op.drop_index(op.f("ix_products_brand_id"), table_name="products")
    op.drop_index(op.f("ix_products_barcode"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_import_files_tenant_id"), table_name="import_files")
    op.drop_index(op.f("ix_import_files_supplier_id"), table_name="import_files")
    op.drop_index(op.f("ix_import_files_brand_id"), table_name="import_files")
    op.drop_table("import_files")
    op.drop_index(op.f("ix_import_batches_tenant_id"), table_name="import_batches")
    op.drop_index(op.f("ix_import_batches_brand_id"), table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index(op.f("ix_customers_tenant_id"), table_name="customers")
    op.drop_index(op.f("ix_customers_brand_id"), table_name="customers")
    op.drop_table("customers")
    op.drop_index(op.f("ix_brand_features_brand_id"), table_name="brand_features")
    op.drop_table("brand_features")
    op.drop_index(op.f("ix_alerts_type"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_tenant_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_brand_id"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_suppliers_tenant_id"), table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_index(op.f("ix_brands_tenant_id"), table_name="brands")
    op.drop_table("brands")
    op.drop_index(op.f("ix_audit_log_tenant_id"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("tenants")
    op.drop_table("channels")
    # ### end Alembic commands ###
    # Enum tipleri tablolarla birlikte düşmez; downgrade'in yeniden upgrade
    # edilebilir olması için açıkça temizlenir.
    for enum_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
